### ISSUE TITLE
Broken by Github?

### ISSUE THREAD

**Issue by tonglil** [danielhusar/github-pr-filter#5]
This seems to not work with the latest update by Github: https://github.com/blog/2123-more-code-review-tools

Any chance for an update?

Once it works again, I want to send a PR to make it work for Firefox :)

**Comment by danielhusar** [comment]
Yeah I noticed that latest updated broke it again :(
Will update it during the weekend.

**Comment by danielhusar** [comment]
Hey, so it should work again.
I published 0.0.4 into chrome store which should be available soon.
Feel free to port it for firefox :)

**Comment by tonglil** [comment]
Woo, thanks Daniel!
